name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest  
    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

        # Build in release mode. Check for compilation errors
      - name: Build (release)
        run: make

        # Build with AddressSanitizer: check for memory bugs
      - name: Build (asan)
        run: make BUILD=asan

        # Smoke test: Initialize all the solvers in dry run: check 
        # if file parser, solver constructor, output file initialization, IC and BC configuration
      - name: Smoke test (dry run, release)
        run: |
          mkdir -p results
          ./solver configs/AdvDiff1D.cfg dry
          ./solver configs/AdvDiff2D.cfg dry
          ./solver configs/Burgers2D.cfg dry
          ./solver configs/IncNS.cfg dry

        # Smoke test with AddressSanitizer: same as smoke test but checking for memory bugs 
      - name: Smoke test (dry run, asan)
        run: |
          ./solver_asan configs/AdvDiff1D.cfg dry
          ./solver_asan configs/AdvDiff2D.cfg dry
          ./solver_asan configs/Burgers2D.cfg dry
          ./solver_asan configs/IncNS.cfg dry
